set shell := [ "nu", "-c" ]

# Default recipe
_default:
    @just --list

# build target wasm
build ARG:
    @wasm-pack build {{ARG}} --target web
    @mkdir ../static/{{ARG}}
    @rsync -avc --delete {{ARG}}/pkg/ ../static/wasm/{{ARG}}/
